sudo: required
language: bash
services:
  - docker
stages:
  - build_and_push
before_script:
  - docker login -u "${DH_USERNAME}" -p "${DH_PASSWORD}"
after_script:
  - docker logout
jobs:
  include:
    # default build with everything
    - stage: build_and_push
      script:
        - make test.docker
        - make publish
