sudo: required
language: bash
services:
  - docker
stages:
  - build_and_push
before_script:
  - docker login -u "${DH_USERNAME}" -p "${DH_PASSWORD}"
after_script:
  - docker logout
.build_script: &build_script
  script:
    - NEXT_TAG="${DH_REPO}:`echo ${GEM_NAME} | sed 's/ /_/g'`-next"
    - echo "${NEXT_TAG}"
    - docker build --no-cache --build-arg BASE_IMAGE_TAG=${BASE_IMAGE_TAG} --build-arg GEM_NAME="${GEM_NAME}" -t ${NEXT_TAG} .;
    - VERSIONS=$(docker run --entrypoint="version-info" ${NEXT_TAG});
    - echo "Installed Versions=${VERSIONS}"
    - VERSION_FLUENTD=$(printf "${VERSIONS}" | grep "fluentd:" | cut -d ":" -f 2);
    - GEM_VERSION=$(printf ${VERSION} | grep fluent-plugin | sed ':a;N;$!ba;s/\n/_/g');
    - PREFIX="fluentd-${VERSION_FLUENTD}_${GEM_VERSION}"
    - BUILD_TAG="${DH_REPO}:${PREFIX}"
    - echo "New Docker Tag=${BUILD_TAG}"
    - _="$(docker pull "${BUILD_TAG}")" && EXIST=$? || :;
    - |
      if [[ "$EXIST" = "0" ]]; then
        printf "[${BUILD_TAG}] found, skipping push\n";
        echo exists;
      else
        printf "[${BUILD_TAG}] not found, pushing to docker hub\n";
        docker tag ${NEXT_TAG} ${BUILD_TAG};
        docker push ${BUILD_TAG};
        docker tag ${BUILD_TAG} ${DH_REPO}:${PREFIX}-latest;
        docker push ${DH_REPO}:${PREFIX}-latest;
      fi
jobs:
  include:
    - stage: build_and_push
      env:
        - BASE_IMAGE_TAG=stable-debian
        - GEM_NAME="fluent-plugin-elasticsearch fluent-plugin-aws-elasticsearch-service"
      <<: *build_script
    - stage: build_and_push
      env:
        - BASE_IMAGE_TAG=stable-debian
        - GEM_NAME="fluent-plugin-elasticsearch"
      <<: *build_script
    - stage: build_and_push
      env:
        - BASE_IMAGE_TAG=stable-debian
        - GEM_NAME="fluent-plugin-aws-elasticsearch"
      <<: *build_script
    - stage: build_and_push
      env:
        - BASE_IMAGE_TAG=v0.14-debian
        - GEM_NAME="fluent-plugin-elasticsearch fluent-plugin-aws-elasticsearch-service"
      <<: *build_script
    - stage: build_and_push
      env:
        - BASE_IMAGE_TAG=v0.14-debian
        - GEM_NAME="fluent-plugin-elasticsearch"
      <<: *build_script
    - stage: build_and_push
      env:
        - BASE_IMAGE_TAG=v0.14-debian
        - GEM_NAME="fluent-plugin-aws-elasticsearch"
      <<: *build_script
    - stage: build_and_push
      env:
        - BASE_IMAGE_TAG=v1.2.6-debian
        - GEM_NAME="fluent-plugin-elasticsearch fluent-plugin-aws-elasticsearch-service"
      <<: *build_script
    - stage: build_and_push
      env:
        - BASE_IMAGE_TAG=v1.2.6-debian
        - GEM_NAME="fluent-plugin-elasticsearch"
      <<: *build_script
    - stage: build_and_push
      env:
        - BASE_IMAGE_TAG=v1.2.6-debian
        - GEM_NAME="fluent-plugin-aws-elasticsearch"
      <<: *build_script

