sudo: required
language: bash
services:
  - docker
stages:
  - build_and_push
before_script:
  - docker login -u "${DH_USERNAME}" -p "${DH_PASSWORD}"
after_script:
  - docker logout
jobs:
  include:
    - stage: build_and_push
      script:
        - NEXT_TAG="${DH_REPO}:next";
        - docker build --build-arg PLUGIN_VER=2.4.0 -t "${NEXT_TAG}" .;
        - VERSIONS=$(docker run --entrypoint="version-info" ${NEXT_TAG});
        - VERSION_FLUENT=$(printf "${VERSIONS}" | grep "fluent:" | cut -d ":" -f 2);
        - VERSION_PLUGIN=$(printf "${VERSIONs}" | grep "fluentd-plugin-elasticsearch:" | cut -d ":" -f 2);
        - BUILD_TAG="${DH_REPO}:fluent-${VERSION_FLUENT}_fluentd-plugin-elasticsearch-${VERSION_PLUGIN}"
        - _="$(docker pull "${BUILD_TAG}")" && EXISTS=$?;
        - |
          if [[ "$EXIST" = "0" ]]; then
            printf "[${BUILD_TAG}] found, skipping push\n";
            echo exists;
          else
            printf "[${BUILD_TAG}] not found, pushing to docker hub\n";
            docker tag ${NEXT_TAG} ${BUILD_TAG};
            docker push ${BUILD_TAG};
            docker tag ${BUILD_TAG} ${DH_REPO}:latest;
            docker push ${DH_REPO}:latest;
          fi



