version: '3.5'
services:
  fluentd:
    build: .
    image: govtechsg/fluentd-elasticsearch:latest
    links:
      - "elasticsearch"
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - 24224:24224 # for fluentd
      - 24231:24231 # for /metrics
  elasticsearch:
    image: elasticsearch
    ports:
      - 9200:9200
  kibana:
    image: kibana
    links:
      - elasticsearch
    ports:
      - 5601:5601
